Core:
    #Print messages to terminal if true
    logEvents: false

    #Place a sign on the cenotaph if true
    cenotaphSign: true

    #Prevent non-Op players from destroying cenotaphs if true (destroyQuickLoot overrides)
    noDestroy: true

    #Show status messages to the player if true
    playerMessage: true

    #Save Cenotaph listing between server reloads if true
    saveCenotaphList: true

    #Stop Cenotaph creation next to existing chests if true
    noInterfere: true

    #Check for new versions on startup
    versionCheck: true

    #Cenotaph normally checks to make sure it isn't trying to create a chest in the void.
    #If you handle or modify the void with another plugin, you can disable that check here.
    #This option should be true for most servers.
    voidCheck: true 

    #If you are not locking your chests with Lockette or LWC but still want them to be
    #protected against Creeper explosions, enable this.
    creeperProtection: false

Removal:
    #Destroy cenotaph on player quickloot if true
    destroyQuickLoot: true

    #Remove cenotaph after removeTime seconds if true
    cenotaphRemove: true
    removeTime: 3600

Security:
    LocketteEnable: true
    lwcEnable: false

    #Remove LWC protection after lwcTimeout seconds
    lwcRemove: false
    lwcTimeout: 3600

    #Set LWC protection to Public instead of removing it after the timeout
    lwcPublic: false