name: Cenotaph
main: com.MoofIT.Minecraft.Cenotaph.Cenotaph
version: 1.3.0
description: Dead Man's Chest mod for Bukkit. Forked from Tombstone by Drakia (TheDgtl) 
author: Southpaw018
website: http://www.moofit.com
commands:
  tomblist:
    description: Show a list of your Tombstones
    usage: /<command> - Show a list of your Tombstones
  tombfind:
    description: |
      Set your compass to point at the designated Tombstone.
      Get the index using /tomblist
    usage: /<command> <index> - Point your compass at the given Tombstone
  tombreset:
    description: Reset your compass to spawn
    usage: /<command>