name: Cenotaph
main: com.MoofIT.Minecraft.Cenotaph.Cenotaph
version: 1.6.3
description: Dead Man's Chest mod for Bukkit. Forked from Tombstone by Drakia (TheDgtl) 
author: Southpaw018
website: http://www.moofit.com
commands:
  cenlist:
    description: Show a list of your Cenotaphs
    usage: /<command> - Show a list of your Cenotaphs
    aliases: [cenotaphlist]
  cenfind:
    description: |
      Set your compass to point at the designated Cenotaph.
      Get the index using /cenotaphlist
    usage: /<command> <index> - Point your compass at the given Cenotaph
    aliases: [cenotaphfind]
  cenreset:
    description: Reset your compass to spawn
    usage: /<command>
    aliases: [cenotaphreset]
  centime:
    description: Show the time left before your cenotaph unlocks or breaks
    usage: /<command> <index>
    aliases: [cenotaphtime]
  cenadmin:
    description: Admin commands for Cenotaph
    usage: /<command> for more usage instructions
    aliases: [cenotaphadmin]
