name: Cenotaph
main: com.MoofIT.Minecraft.Cenotaph.Cenotaph
version: 1.4.1
description: Dead Man's Chest mod for Bukkit. Forked from Tombstone by Drakia (TheDgtl) 
author: Southpaw018
website: http://www.moofit.com
commands:
  cenotaphlist:
    description: Show a list of your Cenotaphs
    usage: /<command> - Show a list of your Cenotaphs
    aliases: [cenlist]
  cenotaphfind:
    description: |
      Set your compass to point at the designated Cenotaph.
      Get the index using /cenotaphlist
    usage: /<command> <index> - Point your compass at the given Cenotaph
    aliases: [cenfind]
  cenotaphreset:
    description: Reset your compass to spawn
    usage: /<command>
    aliases: [cenreset]